apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: noops.customer.upbound.io
spec:
  compositeTypeRef:
    apiVersion: customer.upbound.io/v1alpha1
    kind: XNoOp
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-noopnop-function
    step: nop-function
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
